config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, :start, :end, presence: true
  validates :title, length: { maximum: 20 }
  validates :memo, length: { maximum: 500 }
  validate :start_end_check
  
  def start_end_check
    errors.add(:end, "の日付を正しく記入して下さい。") unless
    self.start < self.end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
    @today = Date.current.to_s(:datetime_jp)
    @schedules_count = Schedule.all.count
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start, :end, :all, :memo))
    if @schedule.save
      flash[:notice] = "予定を新規登録しました"
      redirect_to schedules_path
    else
      render "new"
    end  
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start, :end, :all, :memo))
      flash[:notice] = "「#{@schedule.id}」の予定を更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work11app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <p>スケジュール管理アプリ</p>
    </header>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class="container">
  <%= form_with model: @schedule do |f| %>
		<div class="FormWrapper">
			<h2 class="PageTitle__text">予定を編集してください</h2>
			<div class="FormContainer">
				<form class="">
					<div class="FormTitle">
						<%= f.label :title ,"タイトル" %>
						<%= f.text_field :title %>
					</div>
					<div class="FormStart">
						<%= f.label :start ,"開始日" %>
						<%= f.datetime_field :start %>
					</div>
					<div class="FormEnd">
						<%= f.label :end ,"終了日" %>
						<%= f.datetime_field :end %>
					</div>
					<div class="FormAll__check">
						<%= f.check_box :all, {}, checked_value = "○",unchecked_value = "" %>
						<%= f.label :all ,"終日の場合はチェックを入れます" %>
					</div>
					<div class="FormMemo">
						<%= f.label :memo ,"スケジュールメモ" %>
						<%= f.text_area :memo %>
					</div>
					<div class="FormContainer__buttons">
					    <%= link_to "キャンセル", schedules_path %>
						
						<%= f.submit "保存"%>
					</div>
				</form>
			</div>
		</div>
  <% end %>
</div>

app/views/schedules/index.html.erb
<div class="container">
  
    <% if flash[:notice] %>
     <p class="notice"><%= flash[:notice] %></p>
    <% end %>

  <div class="PageTitle">
    <h2 class="PageTitle__text">予定一覧</h2>
    
    <%= link_to "新規追加", new_schedule_path %>

  </div>

  <div class="table-responsive TableResponsive">
    
    <table class="table Table">
      <thead>
        <tr>
          <th>ID</th>
          <th>タイトル</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>終日</th>
          <th>更新日時</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @schedules.each do |schedule| %>      
          <tr>
            <td>
              <%= schedule.id %>
            </td>

            <td>
              <%= schedule.title %>
            </td>

            <td>
              <%= schedule.start.to_s(:datetime_jp) %>
            </td>

            <td>
              <%= schedule.end.to_s(:datetime_jp) %>
            </td>

            <td>
                <strong><%= schedule.all %></strong>
            </td>

            <td>
              <%= schedule.updated_at.to_s(:datetimeh_jp) %>
            </td>

            <td>
              <%= link_to "詳細", schedule_path(schedule) %>
            </td>

            <td>
              <%= link_to "編集", edit_schedule_path(schedule) %>
            </td>

            <td>
              <%= link_to "削除", schedule_path(schedule), method: :delete, data: { confirm: "本当に削除しますか？" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <footer class="card Footer">
    <div class="card-body FooterBody">
      <p class="FooterBody__count">
        <%= "予定合計 #{@schedules_count}件" %>
          
      </p>

      <p class="FooterBody__datetime">
        <%= "本日の日付 #{@today}" %>
      </p>
    </div>
  </footer>
</div>

app/views/schedules/new.html.erb
<%= form_with model: @schedule do |f| %>
	<div class="container">
		<div class="FormWrapper">
			<h2 class="PageTitle__text">予定の新規追加</h2>
			<div class="FormContainer">
				<form class="">
					<div class="FormTitle">
						<%= f.label :title ,"タイトル" %>
						<%= f.text_field :title %>
					</div>
					<div class="FormStart">
						<%= f.label :start ,"開始日" %>
						<%= f.datetime_field :start %>
					</div>
					<div class="FormEnd">
						<%= f.label :end ,"終了日" %>
						<%= f.datetime_field :end %>
					</div>
					<div class="FormAll__check">
						<%= f.check_box :all, {}, checked_value = "○",unchecked_value = "" %>
						<%= f.label :all ,"終日の場合はチェックを入れます" %>
					</div>
					<div class="FormMemo">
						<%= f.label :memo ,"スケジュールメモ" %>
						<%= f.text_area :memo %>
					</div>
					<div class="FormContainer__buttons">
						<%= link_to "キャンセル", schedules_path %>
						<%= f.submit "登録完了する"%>
					</div>
				</form>
			</div>
		</div>
	</div>
<% end %>

app/views/schedules/show.html.erb
<div class="container">
  <section class="FormWrapper">
    <%= link_to "←一覧に戻る", schedules_path %>
	
    <div class="PageTitle">
        <h2 class="PageTitle__text"><%= @schedule.title %></h2>
        <%= link_to "編集", edit_schedule_path %>
		
	</div>
	
	<div class="FormContainer">
      <table>
	    <tbody>
	      <tr>
	        <th>開始日</th>
			<td><%= @schedule.start.to_s(:datetimeh_jp) %></td>
		  </tr>
		  <tr>
			<th>終了日</th>
			<td><%= @schedule.end.to_s(:datetimeh_jp) %></td>
		  </tr>
		  <tr>
		    <th>終日</th>
			<td><%= @schedule.all %></td>
		  </tr>
		  <tr>
			<th>スケジュールメモ</th>
			<td><%= @schedule.memo %></td>
		  </tr>
		  
		</tbody>
	  </table>
	  
	</div>
  
  </section>
</div>